#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Feb 21, 2020 08:38:56 PM GMT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import main_window_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = MainWindow (root)
    main_window_support.init(root, top)
    root.mainloop()

w = None
def create_MainWindow(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = MainWindow (w)
    main_window_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MainWindow():
    global w
    w.destroy()
    w = None

class MainWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1107x900+470+59")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#595959")
        top.configure(highlightcolor="black")

        self.table_1_canvas = tk.Canvas(top)
        self.table_1_canvas.place(relx=0.289, rely=0.078, relheight=0.168
                , relwidth=0.1)
        self.table_1_canvas.configure(background="#3d3d3d")
        self.table_1_canvas.configure(borderwidth="2")
        self.table_1_canvas.configure(highlightbackground="#000000")
        self.table_1_canvas.configure(highlightthickness="0")
        self.table_1_canvas.configure(selectbackground="#000000")
        self.table_1_canvas.configure(selectborderwidth="0")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.343, rely=0.433, height=31, width=359)
        self.Label1.configure(activebackground="#595959")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(background="#595959")
        self.Label1.configure(font="-family {Courier New} -size 30")
        self.Label1.configure(text='''Your Hand''')

        self.Label1_8 = tk.Label(top)
        self.Label1_8.place(relx=0.343, rely=0.033, height=31, width=359)
        self.Label1_8.configure(activebackground="#595959")
        self.Label1_8.configure(activeforeground="white")
        self.Label1_8.configure(background="#595959")
        self.Label1_8.configure(font="-family {Courier New} -size 30")
        self.Label1_8.configure(text='''Table''')

        self.table_2_canvas = tk.Canvas(top)
        self.table_2_canvas.place(relx=0.397, rely=0.078, relheight=0.168
                , relwidth=0.1)
        self.table_2_canvas.configure(background="#3d3d3d")
        self.table_2_canvas.configure(borderwidth="2")
        self.table_2_canvas.configure(highlightbackground="#000000")
        self.table_2_canvas.configure(highlightthickness="0")
        self.table_2_canvas.configure(selectbackground="#000000")
        self.table_2_canvas.configure(selectborderwidth="0")

        self.table_3_canvas = tk.Canvas(top)
        self.table_3_canvas.place(relx=0.506, rely=0.078, relheight=0.168
                , relwidth=0.1)
        self.table_3_canvas.configure(background="#3d3d3d")
        self.table_3_canvas.configure(borderwidth="2")
        self.table_3_canvas.configure(highlightbackground="#000000")
        self.table_3_canvas.configure(highlightthickness="0")
        self.table_3_canvas.configure(selectbackground="#000000")
        self.table_3_canvas.configure(selectborderwidth="0")

        self.table_4_canvas = tk.Canvas(top)
        self.table_4_canvas.place(relx=0.614, rely=0.078, relheight=0.168
                , relwidth=0.1)
        self.table_4_canvas.configure(background="#3d3d3d")
        self.table_4_canvas.configure(borderwidth="2")
        self.table_4_canvas.configure(highlightbackground="#000000")
        self.table_4_canvas.configure(highlightthickness="0")
        self.table_4_canvas.configure(selectbackground="#000000")
        self.table_4_canvas.configure(selectborderwidth="0")

        self.hand_3_canvas = tk.Canvas(top)
        self.hand_3_canvas.place(relx=0.452, rely=0.256, relheight=0.168
                , relwidth=0.1)
        self.hand_3_canvas.configure(background="#3d3d3d")
        self.hand_3_canvas.configure(borderwidth="2")
        self.hand_3_canvas.configure(highlightbackground="#000000")
        self.hand_3_canvas.configure(highlightthickness="0")
        self.hand_3_canvas.configure(selectbackground="#000000")
        self.hand_3_canvas.configure(selectborderwidth="0")

        self.hand_4_canvas = tk.Canvas(top)
        self.hand_4_canvas.place(relx=0.56, rely=0.256, relheight=0.168
                , relwidth=0.1)
        self.hand_4_canvas.configure(background="#3d3d3d")
        self.hand_4_canvas.configure(borderwidth="2")
        self.hand_4_canvas.configure(highlightbackground="#000000")
        self.hand_4_canvas.configure(highlightthickness="0")
        self.hand_4_canvas.configure(selectbackground="#000000")
        self.hand_4_canvas.configure(selectborderwidth="0")

        self.hand_5_canvas = tk.Canvas(top)
        self.hand_5_canvas.place(relx=0.668, rely=0.256, relheight=0.168
                , relwidth=0.1)
        self.hand_5_canvas.configure(background="#3d3d3d")
        self.hand_5_canvas.configure(borderwidth="2")
        self.hand_5_canvas.configure(highlightbackground="#000000")
        self.hand_5_canvas.configure(highlightthickness="0")
        self.hand_5_canvas.configure(selectbackground="#000000")
        self.hand_5_canvas.configure(selectborderwidth="0")

        self.hand_2_canvas = tk.Canvas(top)
        self.hand_2_canvas.place(relx=0.343, rely=0.256, relheight=0.168
                , relwidth=0.1)
        self.hand_2_canvas.configure(background="#3d3d3d")
        self.hand_2_canvas.configure(borderwidth="2")
        self.hand_2_canvas.configure(highlightbackground="#000000")
        self.hand_2_canvas.configure(highlightthickness="0")
        self.hand_2_canvas.configure(selectbackground="#000000")
        self.hand_2_canvas.configure(selectborderwidth="0")

        self.hand_1_canvas = tk.Canvas(top)
        self.hand_1_canvas.place(relx=0.235, rely=0.256, relheight=0.168
                , relwidth=0.1)
        self.hand_1_canvas.configure(background="#3d3d3d")
        self.hand_1_canvas.configure(borderwidth="2")
        self.hand_1_canvas.configure(highlightbackground="#000000")
        self.hand_1_canvas.configure(highlightthickness="0")
        self.hand_1_canvas.configure(selectbackground="#000000")
        self.hand_1_canvas.configure(selectborderwidth="0")

        self.pile_1_player_canvas = tk.Canvas(top)
        self.pile_1_player_canvas.place(relx=0.56, rely=0.522, relheight=0.457
                , relwidth=0.1)
        self.pile_1_player_canvas.configure(background="#3d3d3d")
        self.pile_1_player_canvas.configure(borderwidth="2")
        self.pile_1_player_canvas.configure(highlightbackground="#000000")
        self.pile_1_player_canvas.configure(highlightthickness="0")
        self.pile_1_player_canvas.configure(selectbackground="#000000")
        self.pile_1_player_canvas.configure(selectborderwidth="0")

        self.pile_2_player_canvas = tk.Canvas(top)
        self.pile_2_player_canvas.place(relx=0.668, rely=0.522, relheight=0.457
                , relwidth=0.1)
        self.pile_2_player_canvas.configure(background="#3d3d3d")
        self.pile_2_player_canvas.configure(borderwidth="2")
        self.pile_2_player_canvas.configure(highlightbackground="#000000")
        self.pile_2_player_canvas.configure(highlightthickness="0")
        self.pile_2_player_canvas.configure(selectbackground="#000000")
        self.pile_2_player_canvas.configure(selectborderwidth="0")

        self.pile_3_player_canvas = tk.Canvas(top)
        self.pile_3_player_canvas.place(relx=0.777, rely=0.522, relheight=0.457
                , relwidth=0.1)
        self.pile_3_player_canvas.configure(background="#3d3d3d")
        self.pile_3_player_canvas.configure(borderwidth="2")
        self.pile_3_player_canvas.configure(highlightbackground="#000000")
        self.pile_3_player_canvas.configure(highlightthickness="0")
        self.pile_3_player_canvas.configure(selectbackground="#000000")
        self.pile_3_player_canvas.configure(selectborderwidth="0")

        self.pile_4_player_canvas = tk.Canvas(top)
        self.pile_4_player_canvas.place(relx=0.885, rely=0.522, relheight=0.457
                , relwidth=0.1)
        self.pile_4_player_canvas.configure(background="#3d3d3d")
        self.pile_4_player_canvas.configure(borderwidth="2")
        self.pile_4_player_canvas.configure(highlightbackground="#000000")
        self.pile_4_player_canvas.configure(highlightthickness="0")
        self.pile_4_player_canvas.configure(selectbackground="#000000")
        self.pile_4_player_canvas.configure(selectborderwidth="0")

        self.pile_4_opponent_canvas = tk.Canvas(top)
        self.pile_4_opponent_canvas.place(relx=0.343, rely=0.522, relheight=0.457
                , relwidth=0.1)
        self.pile_4_opponent_canvas.configure(background="#3d3d3d")
        self.pile_4_opponent_canvas.configure(borderwidth="2")
        self.pile_4_opponent_canvas.configure(highlightbackground="#000000")
        self.pile_4_opponent_canvas.configure(highlightthickness="0")
        self.pile_4_opponent_canvas.configure(selectbackground="#000000")
        self.pile_4_opponent_canvas.configure(selectborderwidth="0")

        self.pile_3_opponent_canvas = tk.Canvas(top)
        self.pile_3_opponent_canvas.place(relx=0.235, rely=0.522, relheight=0.457
                , relwidth=0.1)
        self.pile_3_opponent_canvas.configure(background="#3d3d3d")
        self.pile_3_opponent_canvas.configure(borderwidth="2")
        self.pile_3_opponent_canvas.configure(highlightbackground="#000000")
        self.pile_3_opponent_canvas.configure(highlightthickness="0")
        self.pile_3_opponent_canvas.configure(selectbackground="#000000")
        self.pile_3_opponent_canvas.configure(selectborderwidth="0")

        self.pile_2_opponent_canvas = tk.Canvas(top)
        self.pile_2_opponent_canvas.place(relx=0.126, rely=0.522, relheight=0.457
                , relwidth=0.1)
        self.pile_2_opponent_canvas.configure(background="#3d3d3d")
        self.pile_2_opponent_canvas.configure(borderwidth="2")
        self.pile_2_opponent_canvas.configure(highlightbackground="#000000")
        self.pile_2_opponent_canvas.configure(highlightthickness="0")
        self.pile_2_opponent_canvas.configure(selectbackground="#000000")
        self.pile_2_opponent_canvas.configure(selectborderwidth="0")

        self.pile_1_opponent_canvas = tk.Canvas(top)
        self.pile_1_opponent_canvas.place(relx=0.018, rely=0.522, relheight=0.457
                , relwidth=0.1)
        self.pile_1_opponent_canvas.configure(background="#3d3d3d")
        self.pile_1_opponent_canvas.configure(borderwidth="2")
        self.pile_1_opponent_canvas.configure(highlightbackground="#000000")
        self.pile_1_opponent_canvas.configure(highlightthickness="0")
        self.pile_1_opponent_canvas.configure(selectbackground="#000000")
        self.pile_1_opponent_canvas.configure(selectborderwidth="0")

        self.objective_opponent_canvas = tk.Canvas(top)
        self.objective_opponent_canvas.place(relx=0.018, rely=0.256
                , relheight=0.168, relwidth=0.1)
        self.objective_opponent_canvas.configure(background="#3d3d3d")
        self.objective_opponent_canvas.configure(borderwidth="2")
        self.objective_opponent_canvas.configure(highlightbackground="#000000")
        self.objective_opponent_canvas.configure(highlightthickness="0")
        self.objective_opponent_canvas.configure(selectbackground="#000000")
        self.objective_opponent_canvas.configure(selectborderwidth="0")

        self.objective_player_canvas = tk.Canvas(top)
        self.objective_player_canvas.place(relx=0.885, rely=0.256
                , relheight=0.168, relwidth=0.1)
        self.objective_player_canvas.configure(background="#3d3d3d")
        self.objective_player_canvas.configure(borderwidth="2")
        self.objective_player_canvas.configure(highlightbackground="#000000")
        self.objective_player_canvas.configure(highlightthickness="0")
        self.objective_player_canvas.configure(selectbackground="#000000")
        self.objective_player_canvas.configure(selectborderwidth="0")

        self.end_turn_button = tk.Button(top)
        self.end_turn_button.place(relx=0.136, rely=0.2, height=33, width=120)
        self.end_turn_button.configure(activebackground="#232323")
        self.end_turn_button.configure(activeforeground="white")
        self.end_turn_button.configure(background="#232323")
        self.end_turn_button.configure(borderwidth="0")
        self.end_turn_button.configure(font="-family {Courier New} -size 15")
        self.end_turn_button.configure(foreground="#dddddd")
        self.end_turn_button.configure(highlightbackground="#ffff00")
        self.end_turn_button.configure(highlightthickness="0")
        self.end_turn_button.configure(relief="flat")
        self.end_turn_button.configure(text='''End Turn''')

if __name__ == '__main__':
    vp_start_gui()





